// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyinAppEntity.Database;

#nullable disable

namespace StudyinAppEntity.Migrations
{
    [DbContext(typeof(StudiesContext))]
    [Migration("20230915184122_initialDB")]
    partial class initialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyinAppEntity.Models.Faculty", b =>
                {
                    b.Property<int>("F_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_id"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direction(like Title)");

                    b.HasKey("F_id");

                    b.ToTable("FacultiesTable");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.FacultySubject", b =>
                {
                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("FacultyID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Faculties and Subjects");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("F_id")
                        .HasColumnType("int")
                        .HasColumnName("Faculty ID");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Student's Faculty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Student name")
                        .HasColumnOrder(0);

                    b.HasKey("Id");

                    b.HasIndex("F_id");

                    b.ToTable("StudentsTable");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.StudentSubject", b =>
                {
                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Students and Subjects");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubjectsTable");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.FacultySubject", b =>
                {
                    b.HasOne("StudyinAppEntity.Models.Faculty", "Faculty")
                        .WithMany("FacultySubjects")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyinAppEntity.Models.Subject", "Subject")
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Student", b =>
                {
                    b.HasOne("StudyinAppEntity.Models.Faculty", "Faculty")
                        .WithMany("FacultyStudents")
                        .HasForeignKey("F_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.StudentSubject", b =>
                {
                    b.HasOne("StudyinAppEntity.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyinAppEntity.Models.Subject", "Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Faculty", b =>
                {
                    b.Navigation("FacultyStudents");

                    b.Navigation("FacultySubjects");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("StudyinAppEntity.Models.Subject", b =>
                {
                    b.Navigation("SubjectFaculties");

                    b.Navigation("SubjectStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
